# Generated by Django 2.1.8 on 2019-05-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.TextField(max_length=20, verbose_name='验证码'),
        ),
    ]
